resources:
- name: my-product
  type: git
  source:
    uri: https://github.com/jinsenglin/concourse.git
    branch: master

jobs:
- name: hello-secret
  plan:
  - get: my-product
    trigger: true
  - task: a-thing-that-needs-a-version
    file: my-product/hello-secret-unit.yml
    params:
      branch: {{branch}}
