jobs:
- name: job1
  plan:
  - task: task1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      outputs:
      - name: my-output
      run:
        path: sh
        args:
        - -exec
        - |
          ls my-output
          touch my-output/file
          ls my-output
  - task: task2
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: my-output
      run:
        path: sh
        args:
        - -exec
        - |
          ls my-output
